
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 21 15:56:43 CDT 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CSTRING = 44;
  public static final int STRING_LITERAL = 26;
  public static final int CHAR = 30;
  public static final int EQUALS = 5;
  public static final int ENTERO = 24;
  public static final int DIFERENTE = 7;
  public static final int DOUBLE = 36;
  public static final int RESTA = 32;
  public static final int LLAVEDER = 17;
  public static final int INT = 21;
  public static final int PUNTOCOMA = 2;
  public static final int FOR = 18;
  public static final int IDENTIFICADOR = 23;
  public static final int MENORIGUAL = 9;
  public static final int MENOSNUM = 10;
  public static final int GATO = 6;
  public static final int IOSTREAM = 46;
  public static final int SUMA = 31;
  public static final int MAIN = 22;
  public static final int IF = 19;
  public static final int MASNUM = 12;
  public static final int MAYORIGUAL = 8;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int DECIMAL = 25;
  public static final int error = 1;
  public static final int INCLUDE = 43;
  public static final int CMATH = 41;
  public static final int MENOR = 15;
  public static final int CSTDLIB = 45;
  public static final int CIN = 38;
  public static final int MAYOR = 14;
  public static final int ELSE = 20;
  public static final int COUT = 39;
  public static final int WHILE = 29;
  public static final int LLAVEIZQ = 16;
  public static final int MENOSUNO = 11;
  public static final int CSTDIO = 42;
  public static final int FLOAT = 40;
  public static final int OPEN = 3;
  public static final int EQUALS_EQUALS = 28;
  public static final int BOOLEANO = 27;
  public static final int STRING = 35;
  public static final int MASUNO = 13;
  public static final int CLOSE = 4;
  public static final int DIVISION = 33;
  public static final int MULTIPLICACION = 34;
}

